# Generated by Django 4.2.7 on 2023-11-13 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('psu_passport', models.CharField(max_length=60)),
                ('division', models.CharField(choices=[('ict', 'Information and Communication Technology'), ('cs', 'Computer Science')], max_length=60)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
