# Generated by Django 4.2.7 on 2023-11-14 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0002_alter_studentinfo_division'),
    ]

    operations = [
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='division',
        ),
        migrations.AlterField(
            model_name='studentinfo',
            name='psu_passport',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='division',
            field=models.ManyToManyField(to='app_general.division'),
        ),
    ]
