# Generated by Django 4.2.7 on 2023-11-14 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0003_division_remove_studentinfo_division_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='division',
            name='name',
            field=models.CharField(max_length=60, unique=True),
        ),
        migrations.RemoveField(
            model_name='studentinfo',
            name='division',
        ),
        migrations.AddField(
            model_name='studentinfo',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_general.division'),
        ),
    ]
