# Generated by Django 4.2.7 on 2023-11-14 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0004_alter_division_name_remove_studentinfo_division_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentinfo',
            name='email',
            field=models.EmailField(max_length=60, null=True, unique=True),
        ),
    ]
