# Generated by Django 4.2.7 on 2023-11-14 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0005_studentinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
    ]
