# Generated by Django 4.2.7 on 2023-11-14 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_general', '0006_alter_studentinfo_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentinfo',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_general.division'),
        ),
    ]
